### Site Settings ###
title               : Yash Patel
description         : >-
                      Hi, I am Yash Patel.<br>
                      <a href="https://www.linkedin.com/in/yashpatel0997/">
                      <img border="0" alt="W3Schools" src="Images/l.png" width="30" height="30"> |
                      </a>
                      <a href="https://github.com/yyashpatel">
                      <img border="0" alt="W3Schools" src="Images/github.png"> |
                      </a>
                      <a href="https://github.com/yyashpatel">
                      <img border="0" alt="W3Schools" src="Images/twitter.png">
                      </a>
                     # <a href="https://www.linkedin.com/in/fang-sun-113977113/">LinkedIn </a>
                     # <a href="https://pavan-pk.github.io/projects/">Projects | </a>
                     # <a href="https://github.com/Pavan-pk/resume/blob/main/resume.pdf">Resume | </a>
                      
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : yyashpatel/yyashpatel.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                            # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Yash Patel
  image             : /Images/pic.JPG
# dribbble          : your_username
#  email             : yash.patel@nyu.edu
#  github            : yyashpatel
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
#  linkedin          : yashpatel0997
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : yyash_patel
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
