### Site Settings ###
title               : Yash Patel
description         : >-
                      WELCOME !! <br/>
                      I am a Robotics Graduate Student at <a href="https://wp.nyu.edu/arpl/" target="_top">Agile Robotics and Perception LAB (ARPL)</a>, <a href="https://www.nyu.edu/" target="_top">NYU</a>
                      led by Professor Guiseppe Loianno.
                      I am a Robotics graduate student at NYU. Before joining NYU, I was fortunate to work at <a href="https://minro.org/" target="_top">Machine Intelligence and Robotics Center (MINRO)</a>, 
                      IIIT-Banglore, India under the guidance of <a href="https://www.iiitb.ac.in/faculty/sachit-rao/?name=sachitrao" target="_top">Prof. Sachit Rao</a>.<br />
                      Prior to joining **MINRO,IIIT-B**, I pursued my Bachelor's degree in Mechatronics from <a href="https://www.srmist.edu.in/" target="_top">SRMIST</a>, India.
                      While pursuing my bachelor's degree at  SRMIST I worked in <a href="https://www.srmteamrobocon.com/" target="_top">SRM Team Robocon</a> in the Mechanical and Systems Integration Domain, where I led domain for 2 years.
                      During my final year I did my Bachelor Project on **"Decentralized Control of Robot Swarm for Cooperative Transportation"** at <a href="https://www.researchgate.net/lab/Autonomous-Systems-Lab-Sivanathan-Kandhasamy" target="_top">Autonomous Systems Lab</a>  
                      under the supervision of Prof. K Sivanathan. <br/>
                      My research Interests are in Computer Vision and Robotics. I have worked in the area of Robot Grasping - (restrainted analysis, grasp quality measures, optimization) and Multi-Robot System - (navigation, formation control, obstacle avoidance). 
                      I intend to focus on developing algorithms at the intersection of Computer Vision, Machine Learning and Robotics.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : yyashpatel/yyashpatel.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                            # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Yash Patel
  image             : /Images/pic.JPG
# dribbble          : your_username
  email             : yash.patel@nyu.edu
  github            : yyashpatel
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : yashpatel0997
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : yyash_patel
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
